# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
