# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comanda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default='0', max_digits=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='comb',
            new_name='prod',
        ),
        migrations.AddField(
            model_name='comanda',
            name='produto',
            field=models.ManyToManyField(to='produtos.prod'),
        ),
    ]
