# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_prod_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='produto',
        ),
        migrations.AddField(
            model_name='comanda',
            name='produtos',
            field=models.ManyToManyField(to='produtos.prod_item'),
        ),
    ]
