# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20180814_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_item',
            name='produto',
        ),
        migrations.AddField(
            model_name='prod_item',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.prod'),
            preserve_default=False,
        ),
    ]
