# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20180814_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='pagamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
