# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_montar_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='montados',
            field=models.ManyToManyField(to='produtos.montar_item'),
        ),
    ]
