# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_comanda_montados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montar_item',
            name='total',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
    ]
