# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.CharField(choices=[('1', 'Aberto'), ('2', 'Paga')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_venc', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_cad', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
